In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Melbourne.csv')

In [3]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [4]:
col = ['Suburb','Rooms','Type','Method','SellerG','Regionname','Propertycount','Distance','CouncilArea','Bedroom2','Bathroom','Car','Landsize','BuildingArea','Price']
df = df[col]

In [5]:
df

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.0,NaN,1480000.0
34853,Yarraville,2,h,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.0,104.0,888000.0
34854,Yarraville,2,t,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.0,120.0,705000.0
34855,Yarraville,3,h,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,NaN,NaN,NaN,NaN,NaN,1140000.0
34856,Yarraville,2,h,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.0,103.0,1020000.0

In [6]:
df.nunique()

Suburb            351
Rooms              12
Type                3
Method              9
SellerG           388
Regionname          8
Propertycount     342
Distance          215
CouncilArea        33
Bedroom2           15
Bathroom           11
Car                15
Landsize         1684
BuildingArea      740
Price            2871
dtype: int64

In [85]:
df.dropna(inplace = True)

In [86]:
df

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Abbotsford,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
2,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0,1035000.0,1,...,0,0,0,0,0,0,0,0,1,0
4,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0,1465000.0,1,...,0,0,0,0,0,0,0,0,1,0
6,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0,1600000.0,1,...,0,0,0,0,0,0,0,0,1,0
11,3,4019.0,2.5,4.0,2.0,0.0,245.0,210.0,1876000.0,1,...,0,0,0,0,0,0,0,0,1,0
14,2,4019.0,2.5,2.0,1.0,2.0,256.0,107.0,1636000.0,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,2940.0,25.5,3.0,2.0,2.0,383.0,118.0,500000.0,0,...,0,0,0,0,0,0,1,0,0,0
34849,3,2940.0,25.5,3.0,2.0,2.0,404.0,158.0,570000.0,0,...,0,0,0,0,0,0,1,0,0,0
34853,2,6543.0,6.3,2.0,2.0,1.0,98.0,104.0,888000.0,0,...,0,0,0,0,0,0,0,0,0,0
34854,2,6543.0,6.3,2.0,1.0,2.0,220.0,120.0,705000.0,0,...,0,0,0,0,0,0,0,0,0,0
34856,2,6543.0,6.3,2.0,1.0,0.0,250.0,103.0,1020000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df = pd.get_dummies(df,dtype = 'int')
x = df.drop(columns = 'Price')
y = df['Price']

In [10]:
df

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Abbotsford,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
2,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0,1035000.0,1,...,0,0,0,0,0,0,0,0,1,0
4,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0,1465000.0,1,...,0,0,0,0,0,0,0,0,1,0
6,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0,1600000.0,1,...,0,0,0,0,0,0,0,0,1,0
11,3,4019.0,2.5,4.0,2.0,0.0,245.0,210.0,1876000.0,1,...,0,0,0,0,0,0,0,0,1,0
14,2,4019.0,2.5,2.0,1.0,2.0,256.0,107.0,1636000.0,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,2940.0,25.5,3.0,2.0,2.0,383.0,118.0,500000.0,0,...,0,0,0,0,0,0,1,0,0,0
34849,3,2940.0,25.5,3.0,2.0,2.0,404.0,158.0,570000.0,0,...,0,0,0,0,0,0,1,0,0,0
34853,2,6543.0,6.3,2.0,2.0,1.0,98.0,104.0,888000.0,0,...,0,0,0,0,0,0,0,0,0,0
34854,2,6543.0,6.3,2.0,1.0,2.0,220.0,120.0,705000.0,0,...,0,0,0,0,0,0,0,0,0,0
34856,2,6543.0,6.3,2.0,1.0,0.0,250.0,103.0,1020000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
x

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Suburb_Abbotsford,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
2,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0,1,0,...,0,0,0,0,0,0,0,0,1,0
6,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0,1,0,...,0,0,0,0,0,0,0,0,1,0
11,3,4019.0,2.5,4.0,2.0,0.0,245.0,210.0,1,0,...,0,0,0,0,0,0,0,0,1,0
14,2,4019.0,2.5,2.0,1.0,2.0,256.0,107.0,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,2940.0,25.5,3.0,2.0,2.0,383.0,118.0,0,0,...,0,0,0,0,0,0,1,0,0,0
34849,3,2940.0,25.5,3.0,2.0,2.0,404.0,158.0,0,0,...,0,0,0,0,0,0,1,0,0,0
34853,2,6543.0,6.3,2.0,2.0,1.0,98.0,104.0,0,0,...,0,0,0,0,0,0,0,0,0,0
34854,2,6543.0,6.3,2.0,1.0,2.0,220.0,120.0,0,0,...,0,0,0,0,0,0,0,0,0,0
34856,2,6543.0,6.3,2.0,1.0,0.0,250.0,103.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
y

2        1035000.0
4        1465000.0
6        1600000.0
11       1876000.0
14       1636000.0
           ...
34847     500000.0
34849     570000.0
34853     888000.0
34854     705000.0
34856    1020000.0
Name: Price, Length: 9244, dtype: float64

In [13]:
from sklearn.linear_model import Lasso

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [16]:
reg1 = Lasso(alpha=50, max_iter = 100, tol = 0.1)
reg1.fit(x_train,y_train)

C:\Users\Mouliswaran\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 418753033903956.3, tolerance: 304143885086093.44
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100, tol=0.1)

In [17]:
reg1.score(x_train,y_train)

0.7383292869760225

In [18]:
reg1.score(x_test,y_test)

0.6934380951198058

In [20]:
from sklearn.linear_model import LinearRegression

In [45]:
x1_train,x1_test,y1_train,y1_test = train_test_split(x,y,test_size =0.30)
model = LinearRegression()
model.fit(x1_train,y1_train)

LinearRegression()

In [46]:
model.score(x1_train,y1_train)

0.7284890985856068

In [47]:
model.score(x1_test,y1_test)

0.7129829443957042

In [54]:
newdf = pd.read_csv('tourist_places.csv')

In [55]:
newdf

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,None,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,None,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,None,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,None,Scientific,Yes,0.31,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,320,Western,Gujarat,Gandhinagar,Akshardham,Temple,1992,3.0,4.6,0,Yes,Monday,Religious,No,0.18,All
321,321,Central,Uttar Pradesh,Agra,Agra Fort,Fort,1565,2.0,4.5,40,Yes,None,Historical,Yes,1.30,Afternoon
322,322,Central,Madhya Pradesh,Bhopal,Madhya Pradesh Tribal Museum,Museum,2013,2.0,4.7,10,Yes,Monday,Cultural,Yes,0.15,All
323,323,Northern,Rajasthan,Jaipur,City Palace,Palace,1727,2.0,4.4,200,Yes,None,Historical,Yes,0.51,Morning
324,324,Northern,Rajasthan,Jaipur,Albert Hall Museum,Museum,1887,2.0,4.5,200,Yes,None,Historical,Yes,0.63,All

In [72]:
newdf = newdf.drop(newdf[newdf['Entrance Fee in INR'] == 0].index)

In [73]:
newdf

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,None,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,None,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,None,Scientific,Yes,0.31,Morning
7,7,Northern,Delhi,Delhi,Red Fort,Fort,1648,2.0,4.5,35,Yes,None,Historical,Yes,1.50,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,318,Northern,Delhi,New Delhi,Rail Museum,Museum,1977,2.0,4.4,50,Yes,Monday,Cultural,Yes,0.24,Morning
321,321,Central,Uttar Pradesh,Agra,Agra Fort,Fort,1565,2.0,4.5,40,Yes,None,Historical,Yes,1.30,Afternoon
322,322,Central,Madhya Pradesh,Bhopal,Madhya Pradesh Tribal Museum,Museum,2013,2.0,4.7,10,Yes,Monday,Cultural,Yes,0.15,All
323,323,Northern,Rajasthan,Jaipur,City Palace,Palace,1727,2.0,4.4,200,Yes,None,Historical,Yes,0.51,Morning
324,324,Northern,Rajasthan,Jaipur,Albert Hall Museum,Museum,1887,2.0,4.5,200,Yes,None,Historical,Yes,0.63,All

In [81]:
x = ['Type','Google review rating','Number of google review in lakhs']
y = ['Entrance Fee in INR']
x = newdf[x]
y = newdf[y]

KeyError: "['Type'] not in index"

In [76]:
model = LinearRegression()

In [78]:
newdf = pd.get_dummies(newdf)

In [84]:
newdf

,Unnamed: 0,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Number of google review in lakhs,Zone_Central,Zone_Eastern,Zone_North Eastern,Zone_Northern,Zone_Southern,...,Significance_Scientific,Significance_Sports,Significance_Wildlife,DSLR Allowed_No,DSLR Allowed_Yes,Best Time to visit_Afternoon,Best Time to visit_All,Best Time to visit_All,Best Time to visit_Evening,Best Time to visit_Morning
1,1,2.0,4.5,30,0.40,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,0
2,2,5.0,4.6,60,0.40,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,0
3,3,2.0,4.1,50,0.27,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
4,4,2.0,4.2,15,0.31,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,1
7,7,2.0,4.5,35,1.50,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,318,2.0,4.4,50,0.24,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
321,321,2.0,4.5,40,1.30,1,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
322,322,2.0,4.7,10,0.15,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
323,323,2.0,4.4,200,0.51,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
324,324,2.0,4.5,200,0.63,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0

In [80]:
model.fit(x,y)

ValueError: could not convert string to float: 'Tomb'